name: Build and Push to Docker Hub with Version

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set image tag
      id: vars
      run: |
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        TAG="v1.0.${{ github.run_number }}"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "sha=$SHORT_SHA" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image with tags
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-second-webapp:latest \
                     -t ${{ secrets.DOCKER_USERNAME }}/my-second-webapp:${{ steps.vars.outputs.tag }} .

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-second-webapp:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-second-webapp:${{ steps.vars.outputs.tag }}
